# Generated by Django 4.2.1 on 2023-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacks_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
